### PR TITLE
Mouse-following tooltip and onHide functionality added

### PR DESCRIPTION
**Pull request by ivansieder**
Updated dependencies, tests and added the following properties:
- `followMouse` - When the mouse is over the element, the tooltip will follow along (for best results, combine with `offset`)
- `onHide` - Function to be executed, as soon as the tooltip gets hidden. For best results, combine with onHideDelay.
- `onHideDelay` - Number: Time in milliseconds to wait, before executing the onHide method after the hide sequence has been initialized (e.g. if you use css-transitions to fade out the tooltip after it's been hidden with css)

@Akryum would love to hear your feedback and opinion on this!

### CODE REVIEW

**Comment by MohdAnas** [comment]
Can we merge this?

**Comment by MohdAnas** [comment]
Can we merge this PR?

**Comment by ivansieder** [comment]
@MohdAnas I guess there are too many diverging aspects by now. As this PR did not get any reply, I didn't make an effort to update it so far.

**Comment by MohdAnas** [comment]
Ohk Got it, Can you please tell how to make v-tooltip follow mouse? I am using https://github.com/Akryum/v-tooltip

**Comment by ivansieder** [comment]
maybe @Akryum himself could take a look again and evaluate if it makes sense or not. In that case, the merge could be updated to be aligned with the latest master and then you could eventually use it from the official repo. Other than that, you can fork the repo, try to merge my PR into it and keep a separate repo just for you (which I wouldn't recommend, as it makes updating a lot harder).

**Comment by MohdAnas** [comment]
Thanks @ivansieder for your quick response. I really appreciate it. Thanks again.

**Pull request closed without merging**
