### PR TITLE
Fix Auto Close - Check element contains before the delay

### PR DESCRIPTION
**Pull request by bentleyo**
This is another version of pull request #181.
It fixes an issue when clicking an element in a popover that gets removed from the DOM.

It works by checking `contains` before `requestAnimationFrame` at which point the element has been removed from the DOM and `contains` returns false.

### CODE REVIEW

**Comment by digistorm** [comment]
Hi @Akryum is there anything you need in order for this to be merged?

**Comment by bentleyo** [comment]
Hi @Akryum is there anything you need in order for this to be merged?

**Comment by bondarev** [comment]
Hi, @Akryum when it will be merged or fixed?

**Comment by Akryum** [comment]
A fix was released in v2.0.2

**Pull request closed without merging**
